tasks:
  - name: initialize
    before: |
      echo "🚀 intalling Capsule Runner..."
      CAPSULE_VERSION="v0.2.8"
      wget -O - https://raw.githubusercontent.com/bots-garden/capsule/${CAPSULE_VERSION}/install-capsule-launcher.sh| bash
    init: |
      echo "🚀 intalling Capsule Builder (cabu)..."
      CAPSULE_BUILDER_VERSION="v0.0.2"
      wget -O - https://raw.githubusercontent.com/bots-garden/capsule-function-builder/${CAPSULE_BUILDER_VERSION}/install-capsule-builder.sh | bash

ports:
  - port: 3000-25000
    visibility: public
    onOpen: ignore

vscode:
  extensions:
    - golang.go
    - pkief.material-icon-theme
    - aaron-bond.better-comments
    - PKief.material-icon-theme
